// inertia/components/SidebarLeft.vue
<script setup lang="ts">
import NavFavorites from '~/components/NavFavorites.vue'

import NavMain from '~/components/NavMain.vue'
import NavSecondary from '~/components/NavSecondary.vue'
import NavWorkspaces from '~/components/NavWorkspaces.vue'
import TeamSwitcher from '~/components/TeamSwitcher.vue'
import {
  Sidebar,
  SidebarContent,
  SidebarHeader,
  type SidebarProps,
  SidebarRail,
} from '~/components/ui/sidebar'
import {
  AudioWaveform,
  Blocks,
  Calendar,
  Command,
  Home,
  Inbox,
  MessageCircleQuestion,
  Search,
  Settings2,
  Sparkles,
  Trash2,
} from 'lucide-vue-next'

const props = defineProps<SidebarProps>()

// This is sample data.
const data = {
  teams: [
    {
      name: 'Acme Inc',
      logo: Command,
      plan: 'Enterprise',
    },
    {
      name: 'Acme Corp.',
      logo: AudioWaveform,
      plan: 'Startup',
    },
    {
      name: 'Evil Corp.',
      logo: Command,
      plan: 'Free',
    },
  ],
  navMain: [
    {
      title: 'Search',
      url: '#',
      icon: Search,
    },
    {
      title: 'Ask AI',
      url: '#',
      icon: Sparkles,
    },
    {
      title: 'Home',
      url: '#',
      icon: Home,
      isActive: true,
    },
    {
      title: 'Inbox',
      url: '#',
      icon: Inbox,
      badge: '10',
    },
  ],
  navSecondary: [
    {
      title: 'Calendar',
      url: '#',
      icon: Calendar,
    },
    {
      title: 'Settings',
      url: '#',
      icon: Settings2,
    },
    {
      title: 'Templates',
      url: '#',
      icon: Blocks,
    },
    {
      title: 'Trash',
      url: '#',
      icon: Trash2,
    },
    {
      title: 'Help',
      url: '#',
      icon: MessageCircleQuestion,
    },
  ],
  favorites: [
    {
      name: 'Project Management & Task Tracking',
      url: '#',
      emoji: '📊',
    },
    {
      name: 'Family Recipe Collection & Meal Planning',
      url: '#',
      emoji: '🍳',
    },
    {
      name: 'Fitness Tracker & Workout Routines',
      url: '#',
      emoji: '💪',
    },
    {
      name: 'Book Notes & Reading List',
      url: '#',
      emoji: '📚',
    },
    {
      name: 'Sustainable Gardening Tips & Plant Care',
      url: '#',
      emoji: '🌱',
    },
    {
      name: 'Language Learning Progress & Resources',
      url: '#',
      emoji: '🗣️',
    },
    {
      name: 'Home Renovation Ideas & Budget Tracker',
      url: '#',
      emoji: '🏠',
    },
    {
      name: 'Personal Finance & Investment Portfolio',
      url: '#',
      emoji: '💰',
    },
    {
      name: 'Movie & TV Show Watchlist with Reviews',
      url: '#',
      emoji: '🎬',
    },
    {
      name: 'Daily Habit Tracker & Goal Setting',
      url: '#',
      emoji: '✅',
    },
  ],
  workspaces: [
    {
      name: 'Personal Life Management',
      emoji: '🏠',
      pages: [
        {
          name: 'Daily Journal & Reflection',
          url: '#',
          emoji: '📔',
        },
        {
          name: 'Health & Wellness Tracker',
          url: '#',
          emoji: '🍏',
        },
        {
          name: 'Personal Growth & Learning Goals',
          url: '#',
          emoji: '🌟',
        },
      ],
    },
    {
      name: 'Professional Development',
      emoji: '💼',
      pages: [
        {
          name: 'Career Objectives & Milestones',
          url: '#',
          emoji: '🎯',
        },
        {
          name: 'Skill Acquisition & Training Log',
          url: '#',
          emoji: '🧠',
        },
        {
          name: 'Networking Contacts & Events',
          url: '#',
          emoji: '🤝',
        },
      ],
    },
    {
      name: 'Creative Projects',
      emoji: '🎨',
      pages: [
        {
          name: 'Writing Ideas & Story Outlines',
          url: '#',
          emoji: '✍️',
        },
        {
          name: 'Art & Design Portfolio',
          url: '#',
          emoji: '🖼️',
        },
        {
          name: 'Music Composition & Practice Log',
          url: '#',
          emoji: '🎵',
        },
      ],
    },
    {
      name: 'Home Management',
      emoji: '🏡',
      pages: [
        {
          name: 'Household Budget & Expense Tracking',
          url: '#',
          emoji: '💰',
        },
        {
          name: 'Home Maintenance Schedule & Tasks',
          url: '#',
          emoji: '🔧',
        },
        {
          name: 'Family Calendar & Event Planning',
          url: '#',
          emoji: '📅',
        },
      ],
    },
    {
      name: 'Travel & Adventure',
      emoji: '🧳',
      pages: [
        {
          name: 'Trip Planning & Itineraries',
          url: '#',
          emoji: '🗺️',
        },
        {
          name: 'Travel Bucket List & Inspiration',
          url: '#',
          emoji: '🌎',
        },
        {
          name: 'Travel Journal & Photo Gallery',
          url: '#',
          emoji: '📸',
        },
      ],
    },
  ],
}
</script>

<template>
  <Sidebar class="border-r-0" v-bind="props">
    <SidebarHeader>
      <TeamSwitcher :teams="data.teams" />
      <NavMain :items="data.navMain" />
    </SidebarHeader>
    <SidebarContent>
      <NavFavorites :favorites="data.favorites" />
      <NavWorkspaces :workspaces="data.workspaces" />
      <NavSecondary :items="data.navSecondary" class="mt-auto" />
    </SidebarContent>
    <SidebarRail />
  </Sidebar>
</template>

// src/lib/components/sidebar-left.svelte
<script lang="ts">
	import Blocks from "@lucide/svelte/icons/blocks";
	import Calendar from "@lucide/svelte/icons/calendar";
	import Home from "@lucide/svelte/icons/home";
	import HandCoins from "@lucide/svelte/icons/hand-coins";
	import MessageCircleQuestion from "@lucide/svelte/icons/message-circle-question";
	import SquareChartGantt from "@lucide/svelte/icons/square-chart-gantt";
	import Settings2 from "@lucide/svelte/icons/settings-2";
	import TreePalm from "@lucide/svelte/icons/tree-palm";
	import Trash2 from "@lucide/svelte/icons/trash-2";
	import ListTodo from "@lucide/svelte/icons/list-todo";

	import NavFavorites from "$lib/components/nav-favorites.svelte";
	import NavMain from "$lib/components/nav-main.svelte";
	import NavSecondary from "$lib/components/nav-secondary.svelte";
	import AppName from "$lib/components/app-name.svelte";
	import * as Sidebar from "$lib/components/ui/sidebar/index.js";
	import type { ComponentProps } from "svelte";

	// This is sample data.
	const data = {
		navMain: [
			{
				title: "Home",
				url: "#",
				icon: Home,
				isActive: true,
			},
			{
				title: "Budget Planning",
				url: "#",
				icon: HandCoins,
			},
			{
				title: "Projects",
				url: "#",
				icon: SquareChartGantt,
			},
			{
				title: "Holiday Planning",
				url: "#",
				icon: TreePalm,
			},
			{
				title: "Tasks & Chores",
				url: "#",
				icon: ListTodo,
				badge: "10",
			},
		],
		navSecondary: [
			{
				title: "Calendar",
				url: "#",
				icon: Calendar,
			},
			{
				title: "Settings",
				url: "#",
				icon: Settings2,
			},
			{
				title: "Templates",
				url: "#",
				icon: Blocks,
			},
			{
				title: "Trash",
				url: "#",
				icon: Trash2,
			},
			{
				title: "Help",
				url: "#",
				icon: MessageCircleQuestion,
			},
		],
		favoritesProjects: [
			{
				name: "Project Management & Task Tracking",
				url: "#",
				emoji: "📊",
			},
			{
				name: "Family Recipe Collection & Meal Planning",
				url: "#",
				emoji: "🍳",
			},
			{
				name: "Fitness Tracker & Workout Routines",
				url: "#",
				emoji: "💪",
			},
		],
		favoritesHolidayPlans: [
			{
				name: "Bali with friends",
				url: "#",
				emoji: "🇮🇩",
			},
			{
				name: "Japan with family",
				url: "#",
				emoji: "🇯🇵",
			},
			{
				name: "Road trip in South of France",
				url: "#",
				emoji: "🇫🇷",
			},
		],
	};

	let { ref = $bindable(null), ...restProps }: ComponentProps<typeof Sidebar.Root> = $props();
</script>

<Sidebar.Root class="border-r-0" {...restProps}>
	<Sidebar.Header>
		<AppName />
		<NavMain items={data.navMain} />
	</Sidebar.Header>
	<Sidebar.Content>
		<NavFavorites favoriteTypeName="Projects" favorites={data.favoritesProjects} />
		<NavFavorites favoriteTypeName="Holiday Plans" favorites={data.favoritesHolidayPlans} />
		<NavSecondary items={data.navSecondary} class="mt-auto" />
	</Sidebar.Content>
	<Sidebar.Rail />
</Sidebar.Root>
