// inertia/components/DatePicker.vue
<script setup lang="ts">
import { Calendar } from '~/components/ui/calendar'
import {
  SidebarGroup,
  SidebarGroupContent,
} from '~/components/ui/sidebar'
</script>

<template>
  <SidebarGroup class="px-0">
    <SidebarGroupContent>
      <Calendar class="[&_[role=gridcell].bg-accent]:bg-sidebar-primary [&_[role=gridcell].bg-accent]:text-sidebar-primary-foreground [&_[role=gridcell]]:w-[33px]" />
    </SidebarGroupContent>
  </SidebarGroup>
</template>

// src/lib/components/layout/date-picker.svelte
<script lang="ts">
	import { Calendar } from "$lib/components/ui/calendar/index.js";
	import * as Sidebar from "$lib/components/ui/sidebar/index.js";
</script>

<Sidebar.Group class="px-0">
	<Sidebar.GroupContent>
		<Calendar readonly type="single" class="[&_[role=gridcell]_[role=button][data-today]]:bg-sidebar-primary [&_[role=gridcell]_[role=button][data-today]]:text-sidebar-primary-foreground select-none **:data-bits-calendar-head-cell:w-[33px] [&_[role=gridcell]]:w-[33px]" />
	</Sidebar.GroupContent>
</Sidebar.Group>
